### ISSUE TITLE
vote: tag 1.0.0 

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation-plugin-framework-go#15]
## Release

This would mean tagging [`b708a08`](https://github.com/notaryproject/notation-plugin-framework-go/commit/b708a085c99925d1b57584163f9640c814a62637) as `v1.0.0` to release.

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-plugin-framework-go  v1.0.0`.

- [x] Junjie Gao (@JeyJeyGao)
- [ ] Milind Gokarn (@gokarnm)
- [x] Patrick Zheng (@Two-Hearts)
- [x] Pritesh Bandi (@priteshbandi)
- [ ] Rakesh Gariganti (@rgnote)
- [x] Shiwei Zhang (@shizhMSFT)

## Changes

The code changes to include:

## What's Changed
* Added codeowners and maintainers files by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/1
* Initial commit by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/2
* chore: adding more required functionality by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/5
* chore: fixing UT and adding HasCapability function by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/7
* chore: add license header by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/8
* chore: add various .github related files by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/3
* chore: Adding ReadMe and Makefile by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/11
* chore: Adding UTs and a bug fix by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/10
* Adding validation for request input and added more UTs. by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/12
* chore: Adds e2e tests by @priteshbandi in https://github.com/notaryproject/notation-plugin-framework-go/pull/13
* fix: update error message by @JeyJeyGao in https://github.com/notaryproject/notation-plugin-framework-go/pull/14
* Updated CODEOWNERS and MAINTAINERS files by @toddysm in https://github.com/notaryproject/notation-plugin-framework-go/pull/6
* chore: fix docs and e2e by @shizhMSFT in https://github.com/notaryproject/notation-plugin-framework-go/pull/17
* Bump codecov/codecov-action from 3.1.4 to 3.1.5 by @dependabot in https://github.com/notaryproject/notation-plugin-framework-go/pull/16

**Full Changelog**: https://github.com/notaryproject/notation-plugin-framework-go/compare/e82d02b3fd6400dc02ba694e2c39f7041a42f285...b708a085c99925d1b57584163f9640c814a62637
## Action Requested

Please respond LGTM or REJECT(with reason).

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by Two-Hearts** [comment]
LGTM

**Comment by shizhMSFT** [comment]
@priteshbandi I've made some improvements in #17. Would you take a look?

**Comment by priteshbandi** [comment]
I've updated the commit list and included two more PRs (https://github.com/notaryproject/notation-plugin-framework-go/pull/17, https://github.com/notaryproject/notation-plugin-framework-go/pull/16). 

**Please r-evote**

**Comment by shizhMSFT** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by Two-Hearts** [comment]
LGTM

**Comment by priteshbandi** [comment]
released https://github.com/notaryproject/notation-plugin-framework-go/releases/tag/v1.0.0
